# Generated by Django 4.2.7 on 2024-11-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarians', '0001_initial'),
        ('pet_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='primary_veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_pets', to='veterinarians.veterinarianprofile'),
        ),
    ]
