# Generated by Django 4.2.7 on 2024-11-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0003_remove_medicalrecord_pet_remove_vaccination_pet_and_more'),
        ('veterinarians', '0003_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pet_registration.pet'),
        ),
    ]
