# Generated by Django 4.2.7 on 2024-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarians', '0004_alter_medicalrecord_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('GCASH', 'GCash'), ('MAYA', 'Maya')], max_length=50),
        ),
    ]
